### ISSUE TITLE
Large files not recalled properly from flash storage

### ISSUE THREAD

**Issue by qniens** [SukkoPera/Webbino#5] opened 2019-02-13 14:07 UTC
When loading large files from flash storage the file just stops. The point where the file stops difference from file to file.

For example when trying to load jquery-3.3.1.min.js it stops at character 21.390. The total characters in the file is 86.926. The generated html.h contains the complete file and PROGMEM is also on the correct amount (86.926).

https://code.jquery.com/jquery-3.3.1.min.js

But trying the uncompressed version jquery-3.3.1.js it stops at character 19.969 from the total of 282.113

https://code.jquery.com/jquery-3.3.1.js

But a older custom build jquery file with 57.254 characters just loads fine. (See attached)

Do you have any idea?
[jquery.zip](https://github.com/SukkoPera/Webbino/files/2860636/jquery.zip)

**Comment by SukkoPera** [comment] 2019-02-13 14:37
What version are you using?

**Comment by qniens** [comment] 2019-02-13 15:14
0.10.0git
Cloned yesterday from github

**Comment by SukkoPera** [comment] 2019-02-13 16:57
What board are you using?

**Comment by qniens** [comment] 2019-02-13 17:07
Teensy 3.6

**Comment by SukkoPera** [comment] 2019-02-13 17:12
And what network interface? Please try to provide all the useful information at once, don't have me ask everything...

BTW, Teensy was never tested, I'm surprised it works at all!

**Comment by qniens** [comment] 2019-02-13 18:29
Yes you are right, I'm sorry.
I'm using the Teensy 3.6 with a W5500 network interface.
Attached are the Ino, html.h and the original index.html and jquery.js file.

Smaller files just work as expected. On larger files the browser doesn't timeout or anything.  The file is just incomplete. I also tried disabling Tags and changed the Buffer size. Didn't make a difference.

Do you want me to try it on a ATmega2560 microprocessor? 

Thank you for this amazing library. It has been a huge help for my project.

[main.zip](https://github.com/SukkoPera/Webbino/files/2861614/main.zip)

**Comment by SukkoPera** [comment] 2019-02-14 09:19
I will have a look at it in the weekend.

**Comment by qniens** [comment] 2019-02-14 16:27
Thank you, please let me know if you need more information. If needed, I can send you a Teensy 3.6.

**Comment by SukkoPera** [comment] 2019-04-01 20:32
Finally I had some time to look into this issue, sorry for the delay. The problem is that currently we use an `unsigned int` to hold the filesize. On AVRs, that holds 16 bits, which means the maximum supported file size is 65535 bytes.

In fact, 86.926 mod 65536 = 21390 and 282113 mod 65536 = 19969.

Do you still need support for larger files?

**Comment by qniens** [comment] 2019-04-02 04:00
Hi SukkoPera, yes if possible that would be great!
Do you need a Arduino M0 to test it?

**Comment by SukkoPera** [comment] 2019-04-02 22:17
Well, if you want to donate it to the cause, I won't say no, but I think I can really get away without it :).

Anyway, are you sure you are seeing this problem on a Teensy or another 32-bit board? It should work there, since ints are 32 bits wide on those architectures.

**Comment by qniens** [comment] 2019-04-03 09:29
Yes I'm sure. Can there be a problem with the tag replacement?
I attached a simple demo project. It is the ReplacementTags example from Webbino with only the  include html section different:
```
#include "html.h"

const Page page01 PROGMEM = {index_html_name, index_html, index_html_len, NULL};
const Page page02 PROGMEM = {jquery_js_name, jquery_js, jquery_js_len, NULL};

const Page* const pages[] PROGMEM = {
        &page01,
        &page02,
        NULL
};
```

The web page is a super simple jquery example, which will produce a error because jquery.js only gets partially loaded.

The exact hardware being used:

Arduino M0 clone:
https://robotdyn.com/samd21-m0-mini.html

W5500:
https://www.aliexpress.com/item/Free-Shipping-Q00216-1-Piece-USR-ES1-W5500-Chip-New-SPI-to-LAN-Ethernet-Converter-TCP/32435030006.html?spm=a2g0s.9042311.0.0.404e4c4djaOZk1

Project file + html
[Webbino_test.zip](https://github.com/SukkoPera/Webbino/files/3037859/Webbino_test.zip)

It is no problem to send you the test board + W5500. You have done an amazing job with this library.

**Comment by SukkoPera** [comment] 2019-04-03 10:37
No, I don't think tags have anything to do with it. You can try disabling them to make sure.

But try this first: modify [line 44 of FlashStorage.h](https://github.com/SukkoPera/Webbino/blob/master/src/WebbinoCore/FlashStorage.h#L44) so that instead of
```
return pgm_read_word (&(this -> length));
```
it reads
```
return this -> length;
```
This is a quick hack (and it will break AVR support), if it works I'll come up with a proper fix. So be sure to let me know :).

**Comment by qniens** [comment] 2019-04-03 12:16
Yes this works! Thanks!

Maybe you can add the option in webbino_config.h ?
`#define LARGE_FILE_SUPPORT_ARM`

and a simple 

```
#ifdef LARGE_FILE_SUPPORT_ARM
return this -> length;
#else
return pgm_read_word (&(this -> length));
#endif
```

Maybe not the prettiest way, but it works?

**Comment by SukkoPera** [comment] 2019-04-03 12:52
The final solution will probably be along those lines, but a bit more complicated. I need to think about it a bit. If you don't need to run on AVRs, feel free to keep it like that until I come up with the full fix, it won't hurt.

**Comment by qniens** [comment] 2021-01-09 14:54
Hi SukkoPera, the issue is still present but your quick fix still works. I will close this issue

**Comment by SukkoPera** [comment] 2021-01-09 14:57
Please leave this open, I will fix it properly soon.

**Comment by SukkoPera** [comment] 2021-01-21 21:41
@qniens: I have just commited a tentative fix for this to HEAD, could you please test it?

(Yeah, it's been 2 years and I couldn't come up with anything better...)

**Comment by qniens** [comment] 2021-01-22 09:16
@SukkoPera  Yes the workaround works. `__SIZEOF_INT__` expands to 4 on SAMD51 / M4 chipsets.

You can shorten the preprocessor code to:
`#if __SIZEOF_INT__ == 2 || __SIZEOF_INT__ == 4`
`		return pgm_read_dword (&(this -> length));`
`#else`
`		#error "Mmmmh... Compiling on a weird architecture?"`
`#endif`

You can close this issue if you are satisfied.

**Comment by SukkoPera** [comment] 2021-01-22 18:53
I don't think that would work, since we need to read a `word` when int is 2 bytes and a `dword` when it's 4 :).

Glad it works anyway, it'll be good for the moment, thanks for testing!

**Closed as completed by SukkoPera** 2021-01-22 18:53 UTC
